version: "3"

services:
  nginx:
    build:
      context: ./nginx/ #since docker file is within nginx and config that way
    ports:
      - 80:80
    volumes:
      - ./nginx/html/:/usr/share/nginx/html #mapping the current html path to container path should be based on this file path
      - ./nginx/conf.d/:/etc/nginx/conf.d #mapping the configuration directory

